#header guard
if(STM32F103VBIx_TOOLCHAIN_INCLUDED)
	return()
endif()
set(STM32F103VBIx_TOOLCHAIN_INCLUDED true)

set(CPU_NAME STM32F103VBIx)
set(LINKER_SCRIPT_DIR "${CMAKE_SOURCE_DIR}/cmake/linker-scripts/stm")
set(LINKER_SCRIPT_PRIMARY_FILE "STM32F103VBIx_FLASH.ld")
set(LD_FLAGS "-T${LINKER_SCRIPT_PRIMARY_FILE} -L${LINKER_SCRIPT_DIR}")

list(APPEND LINKER_SCRIPT_DEPENDENCIES
     "${LINKER_SCRIPT_DIR}/${LINKER_SCRIPT_PRIMARY_FILE}")

include(${CMAKE_CURRENT_LIST_DIR}/cortex-m3_softfloat.cmake)
